### ISSUE TITLE
First-Capstone: Peer to Peer Review

### ISSUE THREAD

**Issue by jmoseka** [jasonfelice/First-Capstone#2]
Awesome work! 👍 Project well done. 
✅ Website responsive
✅ Well written code
✅ Professional commit message

However, we noted there are some little details that can be considered to be implemented in order to improve the website. 
- [x] Update Readme file: Kindly update the readme file to include more information as included on this [template](https://github.com/microverseinc/readme-template)
- [x] _Optional_ Kindly consider to add some transition to your site element
- [x] _Optional_ Please consider using comments to your HTML and CSS code

Congrats. Happy Coding 😎

**Comment by jasonfelice** [comment]
I really appreciate your time. Thanks for checking out my project.
