### ISSUE TITLE
Peer-to-Peer Code Review: Capstone Project

### ISSUE THREAD

**Issue by mavericksbalitaan** [jasonfelice/First-Capstone#3]
## Hi @jasonfelice <img src="https://emojis.slackmojis.com/emojis/images/1531849430/4246/blob-sunglasses.gif?1531849430" width="20"/>

![](https://media.giphy.com/media/26BGJadWar1IpmydO/giphy.gif)

### Good Job! 🎉 

- [x] Use HTML semantic tags. ✅ 
- [x] Good CSS styling. ✅ 
- [x] Clean and dry code. ✅ 

### Here are the following suggestions:

- [x] We suggest improving the featured speaker section in the mobile version to align the texts with the image. This is to make it more like the provided template.
- [x] We suggest using a separate script for the about page because when you click on the about link, the console throws an error. It looks for the `speakers-container` which does not exist on the about page.

---
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by jasonfelice** [comment]
I have improved my code according to the suggestions above. Thank You for reviewing my code. :)
